### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by payalchoudhary2410** [wncc/Hello-FOSS-Calci#5]
Handle app crashes by working on the logic. Example: Pressing the "=" button without inputting the second parameter will result in an app crash. More such App crashes have to be worked on.

**Comment by shivamraj6288** [comment]
assign this issue to me

**Comment by payalchoudhary2410** [comment]
Go Ahead

**Comment by shivamraj6288** [comment]
Fixed this

**Comment by payalchoudhary2410** [comment]
Merged!
